server:
  port: 8081

spring:
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://admin:123456@remotehost:27017/admin
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 262174rty
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://127.0.0.1:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 262174rty
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: remotehost
    port: 6379
  aop:
    auto: true

#配置Mybatis
mybatis:
  type-aliases-package: com.wbw.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#打印SQL日志
logging:
  config: classpath:logback-spring.xml
  level:
    com.wbw.demo.dao: debug